[tools]
python = '3.10'
uv = 'latest'
ruff = 'latest'

[env]
_.python.venv = { path = ".venv", create = true }

[hooks]
postinstall = 'uv pip install -r requirements.txt'

[tasks.test]
depends = ["lint"]
run = 'pytest test_dev.py -v'

[tasks.lint]
description = "Lint with ruff"
run = 'ruff check'

[tasks.fix]
description = "Fix Linting Errors"
run = 'ruff check --fix'

[tasks.pip]
description = "Reinstall pip dependencies"
run = 'uv pip install -r requirements.txt'
alias = ['dep', 'dependencies']